version: "3"

services:
  
  hydra-indexer:
    image: joystream/hydra-indexer:latest
    restart: unless-stopped
    environment:
      - DB_NAME=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NEW_BLOCK_TIMEOUT_SEC=150
      - WS_PROVIDER_ENDPOINT_URI=ws://arch.subsocial.network:9944
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*
      ## FIXME: skip very old blocks due to deserialization issues 
      - BLOCK_HEIGHT=460500
      - FORCE_BLOCK_HEIGHT=true
      - TYPES_JSON=typedefs.json
    volumes:
      - ./typedefs.json:/home/hydra/packages/hydra-indexer/typedefs.json
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
    depends_on:
      - redis
      - db
    
  hydra-indexer-gateway:
    image: joystream/hydra-indexer-gateway:latest
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=db 
      - WARTHOG_STARTER_DB_PASSWORD=postgres
      - WARTHOG_STARTER_DB_PORT=5432 
      - WARTHOG_STARTER_DB_USERNAME=postgres 
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
      - DEBUG=index-server:*
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - db
    
  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    
