ARG HYDRA_CLI_VERSION=latest
FROM joystream/hydra-cli:${HYDRA_CLI_VERSION}

COPY schema.graphql /home/hydra
COPY ./mappings /home/hydra/mappings
COPY .env /home/hydra/.env
ADD *.json /home/hydra/

RUN yarn codegen:all

WORKDIR /home/hydra
