version: "3.4"

services:
  indexer-db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: indexer-db
      
  indexer:
    image: joystream/hydra-indexer:2.0.1-beta.9 
    restart: unless-stopped
    environment:
      - INDEXER_WORKERS=5
      - DB_NAME=indexer-db
      - DB_HOST=indexer-db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index*
      - BLOCK_HEIGHT=658170
      - TYPES_JSON=typedefs.json
      - WS_PROVIDER_ENDPOINT_URI=ws://arch.subsocial.network:9944
    volumes:
      - ./typedefs.json:/home/hydra/packages/hydra-indexer/typedefs.json
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
    depends_on: 
      - indexer-db

  indexer-api-gateway:
    image: joystream/hydra-indexer-gateway:2.0.1-beta.9
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=indexer-db 
      - WARTHOG_STARTER_DB_PASSWORD=${DB_PASS}
      - WARTHOG_STARTER_DB_PORT=${DB_PORT}
      - WARTHOG_STARTER_DB_USERNAME=${DB_USER}
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
    ports:
      - "4001:4000" # 
    depends_on:
      - redis
      - indexer
    
  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"
