version: "3"

services:
  processor-gql-server:
    image: hydra:${CLITAG}
    build: ./schema
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_HOST=db
      - DB_USER=postgres 
      - DB_PASS=postgres
      - DB_PORT=5432
      - GRAPHQL_SERVER_HOST=localhost
      - GRAPHQL_SERVER_PORT=4000
    ports:
      - "4000:4000"
    command: ["yarn", "server:start:prod"]

  processor:
    image: hydra:${CLITAG}
    restart: unless-stopped
    environment:
      - TYPEORM_DATABASE=processor-db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - INDEXER_ENDPOINT_URL=http://indexer-api-server:4000/graphql
      - PROCESSOR_POLL_INTERVAL=100 # refresh every second 
      - DEBUG= index-builder:*
    depends_on:
      - indexer-api-server
    command: ["yarn", "processor:start"]
  
  indexer:
    image: hydra:${CLITAG}
    restart: unless-stopped
    environment:
      - TYPEORM_DATABASE=indexer-db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - WS_PROVIDER_ENDPOINT_URI=ws://substrate:9944/
      - REDIS_URI=redis://redis:6379/0
      - DEBUG= index-builder:*
    command: ["yarn", "indexer:start"] 
    depends_on:
      - substrate
      - redis
    
  indexer-api-server:
    image: indexer-api-gateway
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=db 
      - WARTHOG_STARTER_DB_PASSWORD=postgres
      - WARTHOG_STARTER_DB_PORT=5432 
      - WARTHOG_STARTER_DB_USERNAME=postgres 
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - db
    command: ["yarn", "bootstrap:prod"]

    
  substrate:
    image: paritytech/substrate-playground-template-node-template:sha-7212614
    restart: unless-stopped
    ports:
      - "9944:9944"
    command: ["./target/release/node-template", "--dev", "--tmp", "--ws-external"]

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    