version: "3"

services:
  query-node:
    build:
      context: ../..
      target: test
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - GRAPHQL_SERVER_HOST=localhost
      - GRAPHQL_SERVER_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - hydra-processor
    command: yarn query-node:start

  hydra-processor:
    build:
      context: ../..
      target: test
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - GRAPHQL_SERVER_HOST=localhost
      - GRAPHQL_SERVER_PORT=4000
      - INDEXER_ENDPOINT_URL=http://hydra-indexer-gateway:8080/v1/graphql
      - NODE_URL=ws://node-template:9944
      - POLL_INTERVAL_MS=500 # refresh every second
      - DEBUG=hydra*
    ports:
      - "3000:3000"
    depends_on:
      - hydra-indexer-gateway
    command: >
      sh -c "yarn typegen && \
             yarn db:create && \
             npx hydra-cli db:create-migration Initial && \
             yarn db:migrate && \
             yarn processor:migrate && \
             yarn processor:start"

  hydra-indexer:
    build:
      context: ../..
      target: indexer
    restart: unless-stopped
    environment:
      - DB_NAME=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NEW_BLOCK_TIMEOUT_SEC=150000
      - WS_PROVIDER_ENDPOINT_URI=ws://node-template:9944/
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*
      - TYPES_JSON=typedefs.json
    volumes:
      - ./fixtures/typedefs.json:/hydra/packages/hydra-indexer/typedefs.json
    command: >
      sh -c "yarn db:bootstrap && yarn start:prod"
    depends_on:
      - node-template
      - redis
      - db

  hydra-indexer-gateway:
    build:
      context: ../..
      target: indexer-gateway
    restart: unless-stopped
    depends_on:
      - redis
      - db
      - hydra-indexer-status-service
      - hydra-indexer
    ports:
      - "8080:8080"
    environment:
      # DEV_MODE: "true"
      DB_NAME: indexer-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      HYDRA_INDEXER_STATUS_SERVICE: http://hydra-indexer-status-service:8081/status

  hydra-indexer-status-service:
    build:
      context: ../..
      target: indexer-status-service
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      REDIS_URI: redis://redis:6379/0
      PORT: 8081

  node-template:
    image: paritytech/substrate-playground-template-node-template:sha-7212614
    restart: unless-stopped
    ports:
      - "9944:9944"
    command: ["./target/release/node-template", "--dev", "--tmp", "--ws-external"]

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    # command: ["postgres", "-c", "log_statement=all"]
