name: publish
on:
  # When Release Pull Request is merged
  workflow_dispatch:
    inputs:
      manual_release:
        description: 'Manually release current version of hydra-cli'     
        required: true
        default: 'false'

  pull_request:
    branches:
      - master
      - hydra_v1
      - ci-test
    types: [closed]

env:
  CI: true
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true || github.event.inputs.manual_release == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true
          file-name: ./packages/hydra-cli/package.json
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Hydra-cli version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
       
      - name: Setup Node ${{ matrix.node_version }}
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
      - name: Git Identity
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Release Version
        if: steps.check.outputs.changed == 'true'
        shell: bash -ex {0}
        run: |
          RELEASE_VERSION=$(node -p 'require("./packages/hydra-cli/package.json").version')
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Create Git Tag
        if: steps.check.outputs.changed == 'true'
        uses: azu/action-package-version-to-git-tag@v1
        with:
          version: ${{ env.RELEASE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "hydra-cli-v"
      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: |
          yarn workspace @dzlzv/hydra-cli publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}