name: hydra-unit-tests
on: [pull_request]
  
jobs:
  run_unit_tests:
    name: run Hydra unit tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint
        run: |
          yarn 
          yarn workspaces run lint
      - name: run unit tests
        # We use `sudo rm -rf /usr/share/dotnet` as a workaround to free up some space
        # (see hydra-e2e-tests.yml for explaination)
        run: |
          sudo rm -rf /usr/share/dotnet
          yarn  
          yarn workspace @joystream/hydra-cli test 
          yarn workspace @joystream/hydra-typegen test
          yarn workspace @joystream/hydra-common build
          yarn workspace @joystream/hydra-db-utils build
          yarn workspace @joystream/hydra-processor install
          yarn workspace @joystream/hydra-processor test
 
