name: hydra-unit-tests
on: [pull_request, workflow_dispatch]

jobs:
  run_unit_tests:
    name: run Hydra unit tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: lint
        run: yarn workspaces run lint

      - name: run unit tests
        run: ./scripts/test.sh
