name: hydra-e2e-tests
on: [pull_request]
  
jobs:
  run_e2e_tests:
    name: run Hydra e2e tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      #- uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      #  continue-on-error: true
      - name: run e2e tests
        # We use `sudo rm -rf /usr/share/dotnet` as a workaround to free up some space,
        # as suggested in https://github.com/actions/runner-images/issues/2606#issuecomment-772683150
        # because by default the runner will run out of space.
        run: |
          sudo rm -rf /usr/share/dotnet
          yarn 
          yarn build
          yarn e2e-test
 
