name: publish
on:
  workflow_dispatch: # manually run 
    inputs:
      packages:
        description: 'Comma-separated list of packages to publish'
        required: true
        default: '*'
      graduate:
        description: 'Graduate from prerelease'     
        required: false
        default: 'false'
      

env:
  CI: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "always-auth=true" > .npmrc
          echo "@dzlzv:registry=https://registry.npmjs.org/" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install  
        run: |
          yarn install --frozen-lockfile
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Lerna graduate and publish
        if: github.event.inputs.graduate == 'true'
        run: |
          yarn lerna version --conventional-commits --conventional-graduate '${{ github.event.inputs.packages }}' --yes
          yarn lerna publish from-git --dist-tag latest --yes --conventional-commits 

      - name: Lerna publish current package
        if: github.event.inputs.graduate == 'false'
        run: |
          yarn lerna publish from-package --dist-tag next --yes --conventional-commits --conventional-prerelease '${{ github.event.inputs.packages }}'

      - name: Docker login 
        if: "!contains(github.event.inputs.packages, 'hydra-indexer') || github.event.inputs.packages == '*'"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker build
        if: "contains(github.event.inputs.packages, 'hydra-indexer') || github.event.inputs.packages == '*'"
        run: |
          docker build . -t hydra-builder:latest

      - name: Publish hydra-indexer image
        if: "contains(github.event.inputs.packages, 'hydra-indexer') || github.event.inputs.packages == '*'"
        run: |
          (cd ./packages/hydra-indexer && yarn docker:publish)
        env:
          RELEASE_TAG: ${{ github.event.inputs.graduate == 'true' && 'latest' || 'next' }}
        
      - name: Publish hydra-indexer-gateway image
        if: "contains(github.event.inputs.packages, 'hydra-indexer-gateway') || github.event.inputs.packages == '*'"
        run: |
          (cd ./packages/hydra-indexer-gateway && yarn docker:publish)
        env:
          RELEASE_TAG: ${{ github.event.inputs.graduate == 'true' && 'latest' || 'next' }}
        