name: publish
on:
  workflow_dispatch: # manually run 
    inputs:
      graduate:
        description: 'Graduate from prerelease'     
        required: false
        default: 'false'
      

env:
  CI: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "always-auth=true" > .npmrc
          echo "@dzlzv:registry=https://registry.npmjs.org/" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install  
        run: |
          yarn install --frozen-lockfile
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Lerna graduate
        if: github.event.inputs.graduate == 'true'
        run: |
          yarn lerna version --conventional-commits --conventional-graduate --yes

      - name: Lerna publish
        run: |
          yarn lerna publish from-git --dist-tag latest --yes --conventional-commits 
      - name: Docker login 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Publish hydra-indexer image
        run: |
          yarn workspace @dzlzv/hydra-indexer docker:publish 

      - name: Publish hydra-indexer-gateway image
        run: |
          yarn workspace @dzlzv/hydra-indexer-gateway docker:publish
