version: "3"

services:
  substrate:
    image: joystream/node:latest
    ports:
      - "9944:9944"
    command: ["--dev", "--tmp", "--ws-external"]
  
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
